# Generated by Django 4.2.7 on 2023-11-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # noqa E501
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')), # noqa E501
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')), # noqa E501
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
    ]
