# Generated by Django 4.2.7 on 2023-12-22 20:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_tasklabelrelation_task_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                max_length=10000, verbose_name="Description"
            ),
        ),
    ]
